"use client";
import { useEffect,useState } from "react";
import type { FormEvent } from "react";
import type { VaultAdminState,VaultFile } from "@/app/lib/vault-types";
import { downloadFile,fileSize,responseJson } from "../client";
import styles from "../vault.module.css";
type CreatedGrant={id:string;passcode:string;path:string;expiresAt:string};
export default function VaultManager(){
  const [key,setKey]=useState(""),[state,setState]=useState<VaultAdminState|null>(null),[folder,setFolder]=useState(""),[name,setName]=useState(""),[hours,setHours]=useState(48),[file,setFile]=useState<File|null>(null),[grant,setGrant]=useState<CreatedGrant|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{try{setKey(sessionStorage.getItem("sabitx_clearance")||"");}catch{/* Session storage may be disabled. */}},[]);
  async function load(selected=folder){const next=await responseJson<VaultAdminState>(await fetch(`/api/vault/admin${selected?`?folder=${encodeURIComponent(selected)}`:""}`,{headers:{"x-sabitx-key":key.trim()},cache:"no-store"}));setState(next);}
  async function perform(operation:()=>Promise<void>){setBusy(true);setError("");try{await operation();}catch(e){setError(e instanceof Error?e.message:"Request failed.");}finally{setBusy(false);}}
  async function post<T>(body:Record<string,unknown>){return responseJson<T>(await fetch("/api/vault/admin",{method:"POST",headers:{"Content-Type":"application/json","x-sabitx-key":key.trim()},body:JSON.stringify(body)}));}
  function login(event:FormEvent){event.preventDefault();void perform(async()=>{await load();try{sessionStorage.setItem("sabitx_clearance",key.trim());}catch{/* Keep the key in memory only. */}});}
  function createFolder(event:FormEvent){event.preventDefault();void perform(async()=>{const created=await post<{id:string}>({action:"create_folder",name});setName("");setFolder(created.id);setGrant(null);await load(created.id);});}
  function upload(event:FormEvent){event.preventDefault();const uploadForm=event.currentTarget as HTMLFormElement;if(!file||!folder)return;void perform(async()=>{if(file.size>3*1024*1024)throw new Error("This launch supports files up to 3 MB. Larger archives need object storage.");const data=new FormData();data.set("folderId",folder);data.set("file",file);await responseJson(await fetch("/api/vault/admin",{method:"POST",headers:{"x-sabitx-key":key.trim()},body:data}));setFile(null);uploadForm.reset();await load();});}
  function share(){void perform(async()=>{setGrant(await post<CreatedGrant>({action:"create_grant",folderId:folder,hours}));await load();});}
  function revoke(id:string){if(!window.confirm("Revoke this shared link? Its existing sessions will lose access."))return;void perform(async()=>{await post({action:"revoke_grant",grantId:id});if(grant?.id===id)setGrant(null);await load();});}
  function download(item:VaultFile){void perform(()=>downloadFile(item,key.trim()));}
  function lock(){setState(null);setGrant(null);setFolder("");setKey("");try{sessionStorage.removeItem("sabitx_clearance");}catch{}}
  return <main className={styles.page}><header className={styles.nav}><a href="/access">SABITX / RUN</a><a href="/vault">SHARED ACCESS ↗</a></header>
    <section className={styles.header}><p>VAULT / OWNER CONSOLE</p><h1>Access, on<br/><span>your terms.</span></h1><p className={styles.description}>Upload selected files. Issue folder-specific, expiring passcodes. Revoke access without changing your operator key.</p></section>
    {error&&<p className={styles.error} role="alert">{error}</p>}
    {!state?<section className={styles.card}><form onSubmit={login} className={styles.form}><label htmlFor="owner-key">Owner clearance key</label><input id="owner-key" type="password" value={key} onChange={e=>setKey(e.target.value)} required maxLength={1024} autoComplete="off" disabled={busy}/><button disabled={busy}>{busy?"CHECKING…":"OPEN OWNER CONSOLE →"}</button></form></section>:<>
    <div className={styles.toolbar}><span>OWNER CLEARANCE VERIFIED</span><button onClick={lock} disabled={busy}>LOCK CONSOLE</button></div>
    {state.setupRequired?<section className={styles.card}><h2>Initialize the private drive.</h2><p>This creates only the new Vault tables in the existing private database. No existing coding jobs, files or business documents are imported or changed.</p><button disabled={busy} onClick={()=>void perform(async()=>{await post({action:"initialize"});await load();})}>INITIALIZE VAULT</button></section>:<>
    <div className={styles.grid}><section className={styles.card}><h2>Folders</h2><form onSubmit={createFolder} className={styles.form}><label htmlFor="folder-name">New folder name</label><input id="folder-name" value={name} onChange={e=>setName(e.target.value)} maxLength={160} required disabled={busy}/><button disabled={busy}>CREATE FOLDER</button></form><nav className={styles.folderList} aria-label="Private folders">{state.folders.map(item=><button key={item.id} aria-pressed={folder===item.id} disabled={busy} onClick={()=>void perform(async()=>{setFolder(item.id);setGrant(null);await load(item.id);})}>{item.name}<small>{item.file_count} files / {fileSize(item.total_bytes)}</small></button>)}</nav></section>
    <section className={styles.card}><h2>{state.folders.find(item=>item.id===folder)?.name||"Select a folder"}</h2>{folder?<><form onSubmit={upload} className={styles.form}><label htmlFor="vault-upload">Add a file</label><input id="vault-upload" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.md,.csv,.json" onChange={e=>setFile(e.target.files?.[0]||null)} disabled={busy}/><button disabled={busy||!file}>UPLOAD SELECTED FILE</button><small>3 MB per file. Up to 50 files / 50 MB per folder. PDF, images and UTF-8 text. Download-only launch.</small></form><div className={styles.files}>{state.files.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{fileSize(item.size)}</small></div><button disabled={busy} onClick={()=>download(item)}>↓</button></article>)}</div></>:<p>Create or select a folder to manage its files.</p>}</section></div>
    {folder&&<section className={styles.card}><h2>Issue a scoped passcode</h2><div className={styles.toolbar}><label>Expires after <select value={hours} onChange={e=>setHours(Number(e.target.value))} disabled={busy}><option value={1}>1 hour</option><option value={24}>24 hours</option><option value={48}>48 hours</option><option value={168}>7 days</option></select></label><button onClick={share} disabled={busy}>CREATE SHARED ACCESS</button></div><p className={styles.subtle}>This grants read/download access to this folder, including files added later. It never grants coding, operator or other-folder access.</p>
    {grant&&<div className={styles.receipt} role="status"><p>PASSCODE / SHOWN ONCE</p><code>{grant.passcode}</code><p>SHARED LINK</p><a target="_blank" rel="noopener noreferrer" href={grant.path}>{typeof window!=="undefined"?window.location.origin:""}{grant.path}</a><small>Send the link and passcode separately. No message is sent automatically.</small></div>}
    <div className={styles.files}>{state.grants.map(item=><article key={item.id}><div><strong>{item.id.slice(0,8).toUpperCase()} / {item.revoked_at?"REVOKED":new Date(item.expires_at).getTime()<=Date.now()?"EXPIRED":"ISSUED"}</strong><small>Expires {new Date(item.expires_at).toLocaleString()}</small></div>{!item.revoked_at&&<button onClick={()=>revoke(item.id)} disabled={busy}>REVOKE</button>}</article>)}</div></section>}
    </>}
    </>}
    <footer className={styles.footer}><span>NO PUBLIC FILE BUCKET. NO MASTER SHARE CODE.</span><a href="/operator">OPERATOR ↗</a></footer>
  </main>;
}
